name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6 AM UTC
  workflow_dispatch: # Allows you to manually trigger it too

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: gh repo sync "$REPO_NAME" --force
